---
# roles/sudo/tasks/darwin_config.yml

- name: "ensure we tell sudo about sudoers.d (important on OSX)"
  lineinfile:
    dest=/etc/sudoers
    state=present
    regexp='#includedir /etc/sudoers.d'
    line='#includedir /etc/sudoers.d'

- name: "ensure for the /etc/sudoers.d directory on our target (important for OS X)"
  file:
    path: '/etc/sudoers.d'
    state: present
    user: root
    group: wheel
    mode: 0755

- name: Creating sudoers configuration under /etc/sudoers.d
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    validate: "visudo -cf %s"
    owner: root
    group: root
    mode: "0440"
  with_items:
    - "etc/sudoers.d/ansible"
